// Couleurs prédéfinies pour chaque chapitre (fichier partageable Server/Client)
export const SECTION_COLORS = {
  red: {
    bg: "bg-red-100",
    border: "border-red-200",
    text: "text-red-700",
    icon: "text-red-600",
    darkBg: "dark:bg-red-900/20",
    darkBorder: "dark:border-red-800",
    darkText: "dark:text-red-200",
  },
  orange: {
    bg: "bg-orange-100",
    border: "border-orange-200",
    text: "text-orange-700",
    icon: "text-orange-600",
    darkBg: "dark:bg-orange-900/20",
    darkBorder: "dark:border-orange-800",
    darkText: "dark:text-orange-200",
  },
  amber: {
    bg: "bg-amber-100",
    border: "border-amber-200",
    text: "text-amber-700",
    icon: "text-amber-600",
    darkBg: "dark:bg-amber-900/20",
    darkBorder: "dark:border-amber-800",
    darkText: "dark:text-amber-200",
  },
  emerald: {
    bg: "bg-emerald-100",
    border: "border-emerald-200",
    text: "text-emerald-700",
    icon: "text-emerald-600",
    darkBg: "dark:bg-emerald-900/20",
    darkBorder: "dark:border-emerald-800",
    darkText: "dark:text-emerald-200",
  },
  teal: {
    bg: "bg-teal-100",
    border: "border-teal-200",
    text: "text-teal-700",
    icon: "text-teal-600",
    darkBg: "dark:bg-teal-900/20",
    darkBorder: "dark:border-teal-800",
    darkText: "dark:text-teal-200",
  },
  blue: {
    bg: "bg-blue-100",
    border: "border-blue-200",
    text: "text-blue-700",
    icon: "text-blue-600",
    darkBg: "dark:bg-blue-900/20",
    darkBorder: "dark:border-blue-800",
    darkText: "dark:text-blue-200",
  },
  indigo: {
    bg: "bg-indigo-100",
    border: "border-indigo-200",
    text: "text-indigo-700",
    icon: "text-indigo-600",
    darkBg: "dark:bg-indigo-900/20",
    darkBorder: "dark:border-indigo-800",
    darkText: "dark:text-indigo-200",
  },
  violet: {
    bg: "bg-violet-100",
    border: "border-violet-200",
    text: "text-violet-700",
    icon: "text-violet-600",
    darkBg: "dark:bg-violet-900/20",
    darkBorder: "dark:border-violet-800",
    darkText: "dark:text-violet-200",
  },
  purple: {
    bg: "bg-purple-100",
    border: "border-purple-200",
    text: "text-purple-700",
    icon: "text-purple-600",
    darkBg: "dark:bg-purple-900/20",
    darkBorder: "dark:border-purple-800",
    darkText: "dark:text-purple-200",
  },
  pink: {
    bg: "bg-pink-100",
    border: "border-pink-200",
    text: "text-pink-700",
    icon: "text-pink-600",
    darkBg: "dark:bg-pink-900/20",
    darkBorder: "dark:border-pink-800",
    darkText: "dark:text-pink-200",
  },
} as const;

export type SectionColor = typeof SECTION_COLORS[keyof typeof SECTION_COLORS];


